"use strict";

window.ENGLISH_GAME_DATA = Object.freeze({
  stages: [
    {
      id: "case-match",
      title: "אות גדולה וקטנה",
      shortTitle: "A עם a",
      icon: "alphabet-latin.svg",
      instruction: "איזו אות קטנה מתאימה לאות הגדולה?",
    },
    {
      id: "hear-letter",
      title: "שומעים אות",
      shortTitle: "שמעו אות",
      icon: "headphones.svg",
      instruction: "לחצו על הרמקול ובחרו את האות ששמעתם.",
    },
    {
      id: "first-letter",
      title: "אות פותחת",
      shortTitle: "אות ראשונה",
      icon: "sparkles.svg",
      instruction: "שלב 1: לחצו ושמעו את המילה. שלב 2: בחרו באיזו אות היא מתחילה.",
    },
    {
      id: "picture-word",
      title: "מילה ותמונה",
      shortTitle: "בחרו מילה",
      icon: "book-2.svg",
      instruction: "איזו מילה באנגלית מתאימה לתמונה?",
    },
    {
      id: "listen-word",
      title: "שומעים מילה",
      shortTitle: "שמעו מילה",
      icon: "headphones.svg",
      instruction: "לחצו על הרמקול ובחרו את התמונה המתאימה.",
    },
    {
      id: "spell-word",
      title: "בונים מילה",
      shortTitle: "סדרו אותיות",
      icon: "pencil.svg",
      instruction: "לחצו על האותיות לפי הסדר הנכון.",
    },
  ],

  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((upper) => ({
    upper,
    lower: upper.toLowerCase(),
  })),

  words: [
    { word: "apple", hebrew: "תפוח", hebrewVocalized: "תַּפּוּחַ", icon: "apple.svg", color: "#ff6b6b", category: "food" },
    { word: "ball", hebrew: "כדור", hebrewVocalized: "כַּדּוּר", icon: "ball.svg", color: "#f59f00", category: "objects" },
    { word: "cat", hebrew: "חתול", hebrewVocalized: "חָתוּל", icon: "cat.svg", color: "#845ef7", category: "animals" },
    { word: "dog", hebrew: "כלב", hebrewVocalized: "כֶּלֶב", icon: "dog.svg", color: "#339af0", category: "animals" },
    { word: "egg", hebrew: "ביצה", hebrewVocalized: "בֵּיצָה", icon: "egg.svg", color: "#f08c00", category: "food" },
    { word: "fish", hebrew: "דג", hebrewVocalized: "דָּג", icon: "fish.svg", color: "#15aabf", category: "animals" },
    { word: "sun", hebrew: "שמש", hebrewVocalized: "שֶׁמֶשׁ", icon: "sun.svg", color: "#fab005", category: "nature" },
    { word: "book", hebrew: "ספר", hebrewVocalized: "סֵפֶר", icon: "book.svg", color: "#5f3dc4", category: "classroom" },
    { word: "house", hebrew: "בית", hebrewVocalized: "בַּיִת", icon: "house.svg", color: "#e64980", category: "home" },
    { word: "car", hebrew: "מכונית", hebrewVocalized: "מְכוֹנִית", icon: "car.svg", color: "#1971c2", category: "transport" },
    { word: "tree", hebrew: "עץ", hebrewVocalized: "עֵץ", icon: "tree.svg", color: "#2f9e44", category: "nature" },
    { word: "star", hebrew: "כוכב", hebrewVocalized: "כּוֹכָב", icon: "star.svg", color: "#f08c00", category: "nature" },
    { word: "heart", hebrew: "לב", hebrewVocalized: "לֵב", icon: "heart.svg", color: "#f03e3e", category: "body" },
    { word: "moon", hebrew: "ירח", hebrewVocalized: "יָרֵחַ", icon: "moon.svg", color: "#5c7cfa", category: "nature" },
    { word: "milk", hebrew: "חלב", hebrewVocalized: "חָלָב", icon: "milk.svg", color: "#4c6ef5", category: "food" },
    { word: "banana", hebrew: "בננה", hebrewVocalized: "בָּנָנָה", icon: "banana.svg", color: "#e67700", category: "food" },
    { word: "school", hebrew: "בית ספר", hebrewVocalized: "בֵּית סֵפֶר", icon: "school.svg", color: "#6741d9", category: "classroom" },
    { word: "pencil", hebrew: "עיפרון", hebrewVocalized: "עִפָּרוֹן", icon: "pencil.svg", color: "#e8590c", category: "classroom" },
    { word: "eye", hebrew: "עין", hebrewVocalized: "עַיִן", icon: "eye.svg", color: "#0b7285", category: "body" },
    { word: "ear", hebrew: "אוזן", hebrewVocalized: "אֹזֶן", icon: "ear.svg", color: "#c2255c", category: "body" },
    { word: "bed", hebrew: "מיטה", hebrewVocalized: "מִטָּה", icon: "bed.svg", color: "#7048e8", category: "home" },
    { word: "cup", hebrew: "כוס", hebrewVocalized: "כּוֹס", icon: "cup.svg", color: "#1098ad", category: "objects" },
    { word: "cookie", hebrew: "עוגייה", hebrewVocalized: "עוּגִיָּה", icon: "cookie.svg", color: "#d9480f", category: "food" },

    { word: "red", hebrew: "אדום", hebrewVocalized: "אָדוֹם", visualType: "color", visualValue: "#e03131", color: "#e03131", category: "colors" },
    { word: "blue", hebrew: "כחול", hebrewVocalized: "כָּחוֹל", visualType: "color", visualValue: "#1971c2", color: "#1971c2", category: "colors" },
    { word: "green", hebrew: "ירוק", hebrewVocalized: "יָרוֹק", visualType: "color", visualValue: "#2f9e44", color: "#2f9e44", category: "colors" },
    { word: "yellow", hebrew: "צהוב", hebrewVocalized: "צָהֹב", visualType: "color", visualValue: "#f5c000", color: "#f5c000", category: "colors" },
    { word: "black", hebrew: "שחור", hebrewVocalized: "שָׁחוֹר", visualType: "color", visualValue: "#212529", color: "#212529", category: "colors" },
    { word: "white", hebrew: "לבן", hebrewVocalized: "לָבָן", visualType: "color", visualValue: "#ffffff", color: "#74809a", category: "colors" },
    { word: "orange", hebrew: "כתום", hebrewVocalized: "כָּתֹם", visualType: "color", visualValue: "#f76707", color: "#f76707", category: "colors" },
    { word: "pink", hebrew: "ורוד", hebrewVocalized: "וָרֹד", visualType: "color", visualValue: "#e64980", color: "#e64980", category: "colors" },
    { word: "purple", hebrew: "סגול", hebrewVocalized: "סָגֹל", visualType: "color", visualValue: "#7048e8", color: "#7048e8", category: "colors" },
    { word: "brown", hebrew: "חום", hebrewVocalized: "חוּם", visualType: "color", visualValue: "#8d6e63", color: "#8d6e63", category: "colors" },

    { word: "one", hebrew: "אחד", hebrewVocalized: "אֶחָד", visualType: "number", visualValue: "1", color: "#3b5bdb", category: "numbers" },
    { word: "two", hebrew: "שתיים", hebrewVocalized: "שְׁתַּיִם", visualType: "number", visualValue: "2", color: "#1971c2", category: "numbers" },
    { word: "three", hebrew: "שלוש", hebrewVocalized: "שָׁלוֹשׁ", visualType: "number", visualValue: "3", color: "#0b7285", category: "numbers" },
    { word: "four", hebrew: "ארבע", hebrewVocalized: "אַרְבַּע", visualType: "number", visualValue: "4", color: "#2b8a3e", category: "numbers" },
    { word: "five", hebrew: "חמש", hebrewVocalized: "חָמֵשׁ", visualType: "number", visualValue: "5", color: "#5f3dc4", category: "numbers" },
    { word: "six", hebrew: "שש", hebrewVocalized: "שֵׁשׁ", visualType: "number", visualValue: "6", color: "#862e9c", category: "numbers" },
    { word: "seven", hebrew: "שבע", hebrewVocalized: "שֶׁבַע", visualType: "number", visualValue: "7", color: "#a61e4d", category: "numbers" },
    { word: "eight", hebrew: "שמונה", hebrewVocalized: "שְׁמוֹנֶה", visualType: "number", visualValue: "8", color: "#c2255c", category: "numbers" },
    { word: "nine", hebrew: "תשע", hebrewVocalized: "תֵּשַׁע", visualType: "number", visualValue: "9", color: "#e8590c", category: "numbers" },
    { word: "ten", hebrew: "עשר", hebrewVocalized: "עֶשֶׂר", visualType: "number", visualValue: "10", color: "#d9480f", category: "numbers" },

    { word: "horse", hebrew: "סוס", hebrewVocalized: "סוּס", icon: "horse.svg", color: "#8d6e63", category: "animals" },
    { word: "pig", hebrew: "חזיר", hebrewVocalized: "חֲזִיר", icon: "pig.svg", color: "#e64980", category: "animals" },
    { word: "deer", hebrew: "אייל", hebrewVocalized: "אַיָּל", icon: "deer.svg", color: "#c17d3f", category: "animals" },
    { word: "butterfly", hebrew: "פרפר", hebrewVocalized: "פַּרְפַּר", icon: "butterfly.svg", color: "#9c36b5", category: "animals" },
    { word: "bird", hebrew: "ציפור", hebrewVocalized: "צִפּוֹר", icon: "feather.svg", color: "#1098ad", category: "animals" },

    { word: "mother", hebrew: "אמא", hebrewVocalized: "אִמָּא", icon: "woman.svg", color: "#e64980", category: "family" },
    { word: "father", hebrew: "אבא", hebrewVocalized: "אַבָּא", icon: "man.svg", color: "#1971c2", category: "family" },
    { word: "sister", hebrew: "אחות", hebrewVocalized: "אָחוֹת", icon: "user-heart.svg", color: "#d6336c", category: "family" },
    { word: "brother", hebrew: "אח", hebrewVocalized: "אָח", icon: "user-star.svg", color: "#4263eb", category: "family" },
    { word: "baby", hebrew: "תינוק", hebrewVocalized: "תִּינוֹק", icon: "baby-carriage.svg", color: "#f08c00", category: "family" },
    { word: "family", hebrew: "משפחה", hebrewVocalized: "מִשְׁפָּחָה", icon: "users-group.svg", color: "#6741d9", category: "family" },

    { word: "pen", hebrew: "עט", hebrewVocalized: "עֵט", icon: "ballpen.svg", color: "#1971c2", category: "classroom" },
    { word: "eraser", hebrew: "מחק", hebrewVocalized: "מַחַק", icon: "eraser.svg", color: "#e64980", category: "classroom" },
    { word: "ruler", hebrew: "סרגל", hebrewVocalized: "סַרְגֵּל", icon: "ruler.svg", color: "#f59f00", category: "classroom" },
    { word: "bag", hebrew: "תיק", hebrewVocalized: "תִּיק", icon: "backpack.svg", color: "#5f3dc4", category: "classroom" },
    { word: "chair", hebrew: "כיסא", hebrewVocalized: "כִּסֵּא", icon: "armchair.svg", color: "#8d6e63", category: "classroom" },
    { word: "table", hebrew: "שולחן", hebrewVocalized: "שֻׁלְחָן", icon: "table.svg", color: "#c17d3f", category: "classroom" },
    { word: "teacher", hebrew: "מורה", hebrewVocalized: "מוֹרֶה", icon: "chalkboard-teacher.svg", color: "#0b7285", category: "classroom" },
    { word: "notebook", hebrew: "מחברת", hebrewVocalized: "מַחְבֶּרֶת", icon: "notebook.svg", color: "#4263eb", category: "classroom" },

    { word: "bread", hebrew: "לחם", hebrewVocalized: "לֶחֶם", icon: "bread.svg", color: "#c17d3f", category: "food" },
    { word: "cheese", hebrew: "גבינה", hebrewVocalized: "גְּבִינָה", icon: "cheese.svg", color: "#f5c000", category: "food" },
    { word: "water", hebrew: "מים", hebrewVocalized: "מַיִם", icon: "glass.svg", color: "#1c7ed6", category: "food" },
    { word: "cake", hebrew: "עוגה", hebrewVocalized: "עוּגָה", icon: "cake.svg", color: "#e64980", category: "food" },
    { word: "carrot", hebrew: "גזר", hebrewVocalized: "גֶּזֶר", icon: "carrot.svg", color: "#f76707", category: "food" },
    { word: "pizza", hebrew: "פיצה", hebrewVocalized: "פִּיצָה", icon: "pizza.svg", color: "#e8590c", category: "food" },

    { word: "hello", hebrew: "שלום", hebrewVocalized: "שָׁלוֹם", icon: "hand-love-you.svg", color: "#1971c2", category: "greetings" },
    { word: "goodbye", hebrew: "להתראות", hebrewVocalized: "לְהִתְרָאוֹת", icon: "door-exit.svg", color: "#5f3dc4", category: "greetings" },
    { word: "thank you", hebrew: "תודה", hebrewVocalized: "תּוֹדָה", icon: "heart-handshake.svg", color: "#d6336c", category: "greetings" },
    { word: "please", hebrew: "בבקשה", hebrewVocalized: "בְּבַקָּשָׁה", icon: "message-heart.svg", color: "#e64980", category: "greetings" },
    { word: "good morning", hebrew: "בוקר טוב", hebrewVocalized: "בֹּקֶר טוֹב", icon: "sunrise.svg", color: "#f59f00", category: "greetings" },
    { word: "good night", hebrew: "לילה טוב", hebrewVocalized: "לַיְלָה טוֹב", icon: "moon-stars.svg", color: "#5c7cfa", category: "greetings" },
    { word: "yes", hebrew: "כן", hebrewVocalized: "כֵּן", icon: "circle-check.svg", color: "#2f9e44", category: "greetings" },
    { word: "no", hebrew: "לא", hebrewVocalized: "לֹא", icon: "circle-x.svg", color: "#e03131", category: "greetings" },
  ],
});
